IMG_SIZE: 224
BATCH_SIZE: 64
EPOCHS: 1
LEARNING_RATE: 0.0001
SEED: 42
patience: 5 # 조기 종료
DATASET: CustomImageDataset
MODEL: Resnet18Model
TRANSFORMS_PATH: config/transforms_config.yaml

scheduler:
  name: cosine_warm_restart
  params: {
        T_0: 10,
        T_mult: 2,
        eta_min: 0.000001,
    }